name: Build on GitHub Hosted Runner

on:
  push:
    branches:
      - dev
      - copilot/*
  workflow_dispatch:

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - TARGET_CPU_ARCH: x86_64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu/Debian)
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip tree wget curl make m4 rsync

      - name: Download files from bootstrap-sources.list
        run: mkdir -p sources && wget -nv --tries=15 --waitretry=15 -i data/bootstrap-sources.list -P sources

      - name: Enable common functions
        run: chmod +x _common.sh

      - name: Enable staging scripts
        run: chmod +x stage*.sh

      - name: Setup toolchain
        run: |
          ./stage1-setup-toolchain.sh ${{ matrix.TARGET_CPU_ARCH }}
          ls -la .toolchains/${{ matrix.TARGET_CPU_ARCH }}-tools

      - name: Build chroot
        run: |
          ./stage2-build-chroot.sh $PWD/.toolchains/${{ matrix.TARGET_CPU_ARCH }}-tools ${{ matrix.TARGET_CPU_ARCH }} $PWD/rootfs
